[package]
name = "first_interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast = "0.11.0"
dyn-clone = "1.0.17"
once_cell = "1.19.0"
